research_task:
  description: |
    Your task is to analyze a job posting to extract the key skills, experiences,
    and qualifications required for the role. The goal is to create a structured 
    list of these requirements, forming the foundation for effective resume tailoring.

    Here is the URL for the job posting you will be analyzing:
    {job_posting_url}

    Please carefully read through the entire job posting at the provided URL. 
    As you read, identify and categorize the essential requirements mentioned 
    in the posting. Categorize the requirements into the following groups:
    - Technical skills
    - Soft skills
    - Education
    - Years of experience
    - Other qualifications

    Before finalizing your output, double-check the extracted requirements 
    against the original job posting to ensure accuracy and completeness. 
    Make any necessary adjustments to the output.
  expected_output: |
    Please provide your final output as Markdown, with all of the 
    extracted requirements structured in a clear and organized manner.

    <output_format>
    Use Markdown formatting for headings, subheadings, and lists to enhance readability.
    </output_format>

    Remember, the goal is to create a clear, structured list of the key job 
    requirements to help job seekers understand what is needed for the role.
    Analyze the job posting carefully and use the provided tools as needed 
    to ensure an accurate and comprehensive output.

profile_task:
  description: |
    Your task is to create a comprehensive personal and professional profile 
    for an individual based on their GitHub profile and a personal write-up 
    they have provided. The goal is to synthesize information from these 
    sources to highlight the person's skills, experiences, interests, 
    and communication style in a well-rounded profile document.

    First, carefully review the individual's GitHub profile using the URL provided {github_url}.

    Explore their repositories, contributions, and activity to gather relevant 
    information about their technical skills, projects they have worked on, 
    and the programming languages and technologies they are proficient in. 
    Take note of any significant contributions they have made to open-source
     projects or collaborative efforts that demonstrate their ability to work effectively in a team.

    Next, read through the personal write-up provided by the individual:

    ```
    {personal_writeup}
    ```

    Pay attention to the additional context and insights shared in the write-up, 
    such as their educational background, professional experiences, key achievements, 
    and personal interests. Look for examples that highlight their communication skills, 
    problem-solving abilities, and unique qualities that set them apart.

    Now, synthesize the information you have gathered from the GitHub profile 
    and personal write-up to create a comprehensive profile document.
    Use your understanding of the individual's skills, experiences, and interests 
    to paint a holistic picture of their strengths and potential.

    In your profile document, cover the following key areas:

    1. Technical Skills: Highlight the programming languages, frameworks, tools, 
    and technologies the individual is proficient in, backed by examples from 
    their GitHub projects and contributions.

    2. Project Experience: Showcase notable projects the individual has worked on, 
    describing their role, the project's objectives, and the impact of their contributions. 
    Emphasize projects that demonstrate their ability to collaborate effectively and tackle complex challenges.

    3. Contributions and Impact: Discuss significant contributions the individual 
    has made to open-source projects, communities, or organizations. 
    Highlight instances where their work has made a positive impact or solved real-world problems.

    4. Professional Background: Provide an overview of the individual's educational 
    background, work experience, and any relevant certifications or achievements 
    mentioned in their personal write-up.

    5. Communication and Collaboration: Assess the individual's communication 
    style based on their personal write-up and any evidence of effective collaboration 
    found in their GitHub activity. Highlight their ability to articulate ideas, 
    provide constructive feedback, and work well in a team environment.

    6. Interests and Passion: Identify the individual's personal interests and 
    passions based on their GitHub projects and personal write-up. 
    Discuss how these interests align with their professional goals and contribute to their overall profile.

  expected_output: |
    Please structure your profile document in a clear and organized manner, 
    using appropriate headings and subheadings to separate the different sections. 
    Provide specific examples and evidence from the GitHub profile and personal 
    write-up to support your analysis and conclusions.

    <output_format>
    Use Markdown formatting for headings, subheadings, and lists to enhance readability.
    Do not include communication with the other agents in the final output.
    </output_format>

    Remember to maintain a professional and objective tone throughout the profile document, 
    focusing on the individual's strengths, accomplishments, and potential. 
    Avoid making assumptions or subjective judgments without sufficient evidence.

    Before providing your final profile document, take a moment to review the 
    information you have gathered and ensure that your analysis is comprehensive 
    and well-supported. If you have any doubts or need further clarification, 
    you may ask for additional information or context.

    Once you have completed the profile document, please provide it as your final response.

resume_strategy_task:
  description: |
    Using the profile and job requirements obtained from previous tasks, 
    tailor the resume to highlight the most relevant areas. Employ tools to 
    adjust and enhance the resume content. Make sure this is the best resume, but
    don't make up any information. Update every section, as needed. All to better reflect the candidate's
    abilities and how it matches the job posting.

    Please carefully review the candidate's profile, the job requirements, and the existing resume. 

    <scratchpad>
    Brainstorm how to best update and tailor the resume to fit this specific job 
    based on the candidate's profile and qualifications. Consider:
    - What key skills, experiences and accomplishments from the profile and 
    resume best match the job requirements? How can those be highlighted?
    - What parts of the existing resume are less relevant for this job and can 
    be minimized or removed to focus on the most important qualifications?
    - How can the overall resume structure, formatting and language be adjusted 
    to better target this role and employer?
    </scratchpad>
  expected_output: |
    An updated resume that effectively highlights the candidate's
    qualifications and experiences relevant to the job. 

    Update each section of the resume to better highlight the candidate's most 
    relevant abilities and experiences for this job:
    - Rewrite the summary statement to succinctly emphasize the candidate's 
    strongest and most pertinent qualifications. 
    - Restructure and reword the work experience section to focus on achievements 
    and skills that best align with the job requirements.
    - Refine the skills section to feature the skills that are most valuable for this role
    - Adjust the education section if needed to highlight any particularly 
    relevant coursework, projects or training

    Please make sure to retain all of the candidate's factual information and qualifications, 
    but refocus the resume to this specific position. Do not make up any details 
    that are not already provided in the profile or original resume.

    Please output the full updated resume with all of your recommended changes. 
    Make sure the final resume is complete and well-formatted. Assume that the 
    resume will eventually be converted to a PDF for submission, so take this 
    into account when formatting the Markdown. Do not include communication with t
    he other agents in the final output.

interview_preparation_task:
  description: |
    Your task is to generate a set of interview questions and talking points to 
    help a job candidate prepare for an interview, based on the tailored resume a
    nd job requirements. Utilize tools to generate relevant questions and 
    discussion points. Use these inputs to create questions and discussion 
    topics that will allow the candidate to showcase their qualifications and suitability for the position.

    First, carefully review the candidate's resume and the job description. 
    Look for areas where the candidate's skills and experience align with 
    the requirements and responsibilities outlined in the job description. 

    Next, in a brainstorm a list of potential interview 
    questions based on your analysis. Consider questions that will prompt the 
    candidate to discuss their relevant qualifications, experience, and accomplishments. 
    Also think about questions that gauge the candidate's understanding of the 
    role and how their background has prepared them for its specific demands.
  expected_output: |
    After brainstorming, generate a final curated set of interview questions and 
    talking points. Aim to include around 8-10 questions 
    and 3-5 key talking points. Focus on questions and topics that will help 
    the candidate draw clear connections between their resume and the job requirements. 
    The questions should allow them to highlight their most pertinent skills and qualifications.

    The talking points should succinctly capture the main reasons the candidate i
    s a strong fit for the role based on their resume. Phrase the talking points 
    as statements the candidate could work into their interview responses to underscore their suitability.

    Remember, the ultimate goal is to equip the candidate with questions and 
    discussion points that will enable them to effectively convey how their
    background qualifies them for this specific job. Keep this in mind as you craft your final output.
    Do not include communication with the other agents in the final output.