research_task:
  description: |
    Analyze the job posting available at the provided URL ({job_posting_url}). 
    Extract and categorize key skills, experiences, and qualifications required for the position.
    Ensure the analysis is thorough and accurate, and maintain a structured and clear output format.
    Avoid including irrelevant information.

    Steps to follow:
    - Access the job posting at the provided URL.
    - Identify and list key skills mentioned in the job posting.
    - Extract required experiences, including years of experience and specific fields.
    - Determine the essential qualifications and educational requirements.
    - Categorize the extracted information into a structured format.

  expected_output: |
    A concise, structured document containing the following information:
    Key Skills:
    - [List of Skills]

    Required Experiences:
    - [List of Experiences]

    Qualifications:
    - [List of Qualifications]

profile_task:
  description: |
    Compile a concise personal and professional profile using 
    the provided GitHub URL and personal write-up. 
    Extract key information and synthesize it into a cohesive profile.
    Ensure thoroughness, accuracy, and clarity in your analysis.
    Avoid including irrelevant or redundant information.

    Steps to follow:
    - Access the GitHub URL and review the repositories, projects, and contributions.
    - Read the personal write-up to understand the applicant’s background and interests.
    - Identify and list key skills demonstrated in the GitHub projects.
    - Extract detailed project experiences and notable contributions.
    - Highlight the applicant's interests and any relevant details from the personal write-up.
    - Analyze the applicant’s communication style based on the personal write-up and GitHub interactions.

    GitHub URL: {github_url}
    Personal Write-up: {personal_writeup}
  expected_output: |
    A concise profile document in Markdow

resume_strategy_task:
  description: |
    Using the profile and job requirements obtained from
    previous tasks, tailor the resume to highlight the most
    relevant areas. Employ tools to adjust and enhance the
    resume content. Make sure this is the best resume even but
    don't make up any information. Update every section,
    inlcuding the initial summary, work experience, skills,
    and education. All to better reflrect the candidates
    abilities and how it matches the job posting.

    - Run the truncate_prompt tool before making LLM requests.

  expected_output: |
    An updated resume in Markdown that effectively highlights the candidate's 
    qualifications and experiences relevant to the job.
    
interview_preparation_task:
  description: |
    Create a set of potential interview questions and talking points based on the tailored resume and job requirements. Utilize available tools to generate relevant questions and discussion points. Ensure these questions and talking points help the candidate highlight the main points of the resume and how it matches the job posting.
    
    Guidelines:
    - Review the tailored resume and the job requirements thoroughly.
    - Formulate questions that target the candidate's skills, experiences, and qualifications as listed in the resume.
    - Develop talking points that help the candidate draw connections between their resume and the job requirements.
    - Include suggestions on how the candidate can effectively highlight their resume's main points during the interview.

  expected_output: |
    # Interview Preparation Document

    ## Key Interview Questions
    1. [Question 1]
    2. [Question 2]
    3. [Question 3]
    4. [Question 4]
    5. [Question 5]

    ## Relevant Talking Points
    - [Talking Point 1]
    - [Talking Point 2]
    - [Talking Point 3]
    - [Talking Point 4]
    - [Talking Point 5]

    ## Suggestions for Highlighting Resume Main Points
    - [Suggestion 1]
    - [Suggestion 2]
    - [Suggestion 3]
    - [Suggestion 4]
    - [Suggestion 5]

aggregation_task:
  description: |
    "Using the tailored resumes from the resume strategist tasks, 
    tailor the resume to highlight the most
    relevant areas. Employ tools to adjust and enhance the
    resume content. Make sure this is the best resume even but
    don't make up any information. Update every section,
    inlcuding the initial summary, work experience, skills,
    and education. All to better reflrect the candidates
    abilities and how it matches the job posting.

    Guidelines:
    - Review the three input resumes thoroughly.
    - Identify the strengths and weaknesses of each resume.
    - Merge the best elements from each resume, ensuring a coherent and logical structure.
    - Maintain a consistent tone and style throughout the final resume.
    - Do not fabricate any information.
    - Run the truncate_prompt tool before making LLM requests.

    Think step by step. Don't rush. Take your time.
    If you do your BEST work, I will give you a $10,000 bonus.

  expected_output: |
    An updated resume in Markdown that effectively highlights the candidate's 
    qualifications and experiences relevant to the job.
