research_task:
  description: |
    Analyze the job posting available at the provided URL ({job_posting_url}). 
    Extract and categorize key skills, experiences, and qualifications required for the position.
    Ensure the analysis is thorough and accurate, and maintain a structured and clear output format.
    Avoid including irrelevant information.

    Steps to follow:
    - Access the job posting at the provided URL.
    - Identify and list key skills mentioned in the job posting.
    - Extract required experiences, including years of experience and specific fields.
    - Determine the essential qualifications and educational requirements.
    - Categorize the extracted information into a structured format.
  expected_output: |
    Key Skills:
    - [List of Skills]

    Required Experiences:
    - [List of Experiences]

    Qualifications:
    - [List of Qualifications]

profile_task:
  description: |
    Your task is to compile a detailed personal and professional profile using 
    the provided GitHub URL and personal write-up. 
    Extract key information and synthesize it into a cohesive profile.
    Ensure thoroughness, accuracy, and clarity in your analysis.
    Avoid including irrelevant or redundant information.

    Steps to follow:
    - Access the GitHub URL and review the repositories, projects, and contributions.
    - Read the personal write-up to understand the applicant’s background and interests.
    - Identify and list key skills demonstrated in the GitHub projects.
    - Extract detailed project experiences and notable contributions.
    - Highlight the applicant's interests and any relevant details from the personal write-up.
    - Analyze the applicant’s communication style based on the personal write-up and GitHub interactions.

    GitHub URL: {github_url}
    Personal Write-up: {personal_writeup}
  expected_output: |
    A comprehensive profile document that includes:
    - Skills: [List of Skills]
    - Project experiences: [List of Project Experiences]
    - Contributions: [List of Contributions]
    - Interests: [List of Interests]
    - Communication style: [Analysis of Communication Style]

resume_strategy_task:
  description: |
    Using the profile and job requirements obtained from previous tasks, tailor 
    the resume to highlight the most relevant areas. Enhance the resume content 
    by rewording, restructuring, and emphasizing key skills and experiences. Ensure no sections or critical content are removed or significantly altered without good reason. 
    Do not fabricate any information.

    Guidelines:
    - Preserve the candidate's name and contact information.
    - Make the summary impactful and concise, ideally no more than 3-4 lines.
    - Reword and restructure professional experiences to emphasize relevance to the job.
    - Highlight key skills and achievements, ensuring alignment with the job requirements.
    - Maintain a clear and logical structure, enhancing readability and visual appeal.
    - Remove redundant or less relevant information if it improves the resume's focus.
    - Ensure the customized resume has dates and locations consistent with the original resume.
    - Maintain the original voice and style of the candidate's resume as much as possible.
    - Format the resume in clean Markdown, suitable for PDF conversion.

  expected_output: |
    ONLY the customized resume.
    
interview_preparation_task:
  description: |
    Create a set of potential interview questions and talking points based on the tailored resume and job requirements. Utilize available tools to generate relevant questions and discussion points. Ensure these questions and talking points help the candidate highlight the main points of the resume and how it matches the job posting.
    
    Guidelines:
    - Review the tailored resume and the job requirements thoroughly.
    - Formulate questions that target the candidate's skills, experiences, and qualifications as listed in the resume.
    - Develop talking points that help the candidate draw connections between their resume and the job requirements.
    - Include suggestions on how the candidate can effectively highlight their resume's main points during the interview.

  expected_output: |
    # Interview Preparation Document

    ## Key Interview Questions
    1. [Question 1]
    2. [Question 2]
    3. [Question 3]
    4. [Question 4]
    5. [Question 5]

    ## Relevant Talking Points
    - [Talking Point 1]
    - [Talking Point 2]
    - [Talking Point 3]
    - [Talking Point 4]
    - [Talking Point 5]

    ## Suggestions for Highlighting Resume Main Points
    - [Suggestion 1]
    - [Suggestion 2]
    - [Suggestion 3]
    - [Suggestion 4]
    - [Suggestion 5]

file_reading_task:
  description: |
    Read the content of the tailored resume file (tailored_resume.md). Verify that the content is complete and matches the expected structure.

    Guidelines:
    - Open and read the tailored_resume.md file.
    - Verify that the content is complete and matches the expected sections.
    - Ensure there are no missing parts or formatting issues.
    - If the file content is incorrect or incomplete, access the resume strategy task conversation context to extract the correct resume content.
    - If necessary, refer to the resume strategy task conversation context to validate the content.

  expected_output: |
    A document containing the complete content of the tailored resume.
    - File Content: [Content of tailored_resume.md]

resume_validation_task:
  description: |
    Validate the content of the tailored resume obtained from the File Reader Agent. Ensure the resume meets all specified requirements, including completeness, formatting, and correctness.

    Guidelines:
    - Review the content for completeness.
    - Check for formatting consistency and correctness.
    - Ensure all sections are present and correctly structured.

  expected_output: |
    A validation report containing:
    - Completeness Check: [Pass/Fail]
    - Formatting Check: [Pass/Fail]
    - Correctness Check: [Pass/Fail]
    - Detailed Comments: [List of identified issues, if any]

resume_correction_task:
  description: |
    Correct the tailored resume based on the validation report from the Resume Validator Agent. Ensure all identified issues are addressed and the resume is optimized for submission.

    Guidelines:
    - Review the validation report thoroughly.
    - Correct all identified issues related to completeness, formatting, and correctness.
    - Ensure the resume is polished and ready for submission.
    - If necessary, refer to the resume strategy task conversation context to make corrections.

  expected_output: |
    ONLY the corrected resume.
