research_task:
  description: |
    Analyze the job posting available at the provided URL ({job_posting_url}). 
    Extract and categorize key skills, experiences, and qualifications required for the position.
    Ensure the analysis is thorough and accurate, and maintain a structured and clear output format.
    Avoid including irrelevant information.

    Steps to follow:
    - Access the job posting at the provided URL.
    - Identify and list key skills mentioned in the job posting.
    - Extract required experiences, including years of experience and specific fields.
    - Determine the essential qualifications and educational requirements.
    - Categorize the extracted information into a structured format.
  expected_output: |
    Key Skills:
    - [List of Skills]

    Required Experiences:
    - [List of Experiences]

    Qualifications:
    - [List of Qualifications]

profile_task:
  description: |
    Your task is to compile a detailed personal and professional profile using 
    the provided GitHub URL and personal write-up. 
    Extract key information and synthesize it into a cohesive profile.
    Ensure thoroughness, accuracy, and clarity in your analysis.
    Avoid including irrelevant or redundant information.

    Steps to follow:
    - Access the GitHub URL and review the repositories, projects, and contributions.
    - Read the personal write-up to understand the applicant’s background and interests.
    - Identify and list key skills demonstrated in the GitHub projects.
    - Extract detailed project experiences and notable contributions.
    - Highlight the applicant's interests and any relevant details from the personal write-up.
    - Analyze the applicant’s communication style based on the personal write-up and GitHub interactions.

    GitHub URL: {github_url}
    Personal Write-up: {personal_writeup}
  expected_output: |
    A comprehensive profile document that includes:
    - Skills: [List of Skills]
    - Project experiences: [List of Project Experiences]
    - Contributions: [List of Contributions]
    - Interests: [List of Interests]
    - Communication style: [Analysis of Communication Style]

resume_strategy_task:
  description: |
    Using the profile and job requirements obtained from previous tasks, tailor 
    the resume to highlight the most relevant areas. Enhance the resume content 
    by rewording and formatting while ensuring no sections or content are removed or significantly altered. 
    Do not fabricate any information.

    Guidelines:
    - Keep the contact information and the candidate's name consistent.
    - Ensure the summary, if added, is concise, impactful, and no more than 3-4 lines.
    - Do not include communication with other agents in the final output.
    - Do not include ANY delimiters in the final output. For example, do not include 
      markdown ```markdown or ```yaml delimiters.
    - Only incorporate new details if they are verified through research tasks and pertain to the candidate's actual experience (e.g., information found on the candidate's GitHub or personal write-up).
    - Ensure the customized resume has dates and locations consistent with the original resume.
    - Preserve the original voice and style of the candidate's resume.
    - Preserve the original resume's structure and sections.
    - You may edit the existing professional experience, but DO NOT remove any experience.

    If you do your best work, you will I will give you a $10,000 bonus!

  expected_output: |
    "An updated resume that effectively highlights the candidate's
    qualifications and experiences relevant to the job. The output should be in clean Markdown format, 
    ready for PDF conversion."
    
    

interview_preparation_task:
  description: |
    Create a set of potential interview questions and talking points based on the tailored resume and job requirements. Utilize available tools to generate relevant questions and discussion points. Ensure these questions and talking points help the candidate highlight the main points of the resume and how it matches the job posting.
    
    Guidelines:
    - Review the tailored resume and the job requirements thoroughly.
    - Formulate questions that target the candidate's skills, experiences, and qualifications as listed in the resume.
    - Develop talking points that help the candidate draw connections between their resume and the job requirements.
    - Include suggestions on how the candidate can effectively highlight their resume's main points during the interview.

  expected_output: |
    # Interview Preparation Document

    ## Key Interview Questions
    1. [Question 1]
    2. [Question 2]
    3. [Question 3]
    4. [Question 4]
    5. [Question 5]

    ## Relevant Talking Points
    - [Talking Point 1]
    - [Talking Point 2]
    - [Talking Point 3]
    - [Talking Point 4]
    - [Talking Point 5]

    ## Suggestions for Highlighting Resume Main Points
    - [Suggestion 1]
    - [Suggestion 2]
    - [Suggestion 3]
    - [Suggestion 4]
    - [Suggestion 5]
